### ISSUE TITLE
Using match with wildcard route breaks

### ISSUE THREAD

**Issue by tfchristianost** [pillarjs/path-to-regexp#212]
Hello!

I want to use `match` to match a given hash (from our client hash router) to a predefined set of paths, e.g. we have a path `#/user/:id` and I want to have `#/user/123` produce a match. In addition we have a catch-all route, which is `#/*` which should produce a match when I pass in `#/`:

```javascript
const { match } = require('path-to-regexp')

match('#/*')('#/')
```

but it fails with

```
TypeError: Unexpected MODIFIER at 2, expected END
    at mustConsume (/home/runner/node_modules/path-to-regexp/dist/index.js:113:15)
    at parse (/home/runner/node_modules/path-to-regexp/dist/index.js:172:9)
    at stringToRegexp (/home/runner/node_modules/path-to-regexp/dist/index.js:329:27)
    at pathToRegexp (/home/runner/node_modules/path-to-regexp/dist/index.js:403:12)
    at match (/home/runner/node_modules/path-to-regexp/dist/index.js:248:14)
    at /home/runner/index.js:3:1
    at Script.runInContext (vm.js:133:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

See this REPL: https://repl.it/repls/GenuineAssuredControlflowgraph

Is this a bug or is it not supported? Is there a workaround?

This occurs with v6 of your library, in previous version it seemed to be working.

Thanks for your help, I’m happy to share more information if needed!

**Comment by blakeembrey** [comment]
@tfchristianost An asterisk like that hasn't worked since V1, a little over two years ago: https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23. You can read the documentation in the README, there's even a section helping you on this: https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x.

**Comment by tfchristianost** [comment]
Oh wow, I wonder how that worked before then 😅  Thanks for the reply, I’ll have a look into the linked section!
