### ISSUE TITLE
Error on vite build of TypeScript Vue3 project: "match" is not exported

### ISSUE THREAD

**Issue by tikaszvince** [pillarjs/path-to-regexp#309]
Hi

I'm trying to update from 6.2.2 to 7.0.0.
I have a Vue3 project with TypeScript enabled.

```TypeScript
import {match} from 'path-to-regexp';

export function contentMatch(path: string): null | any {
  const urlMatch = match('/posts{/:id}?', {
    decode: decodeURIComponent,
  });
  const result = urlMatch(path);
  if (!result) {
    return null;
  }
  return result.params;
}
```

If I use `import {match} from 'path-to-regexp';` I got a build error. 
```
"match" is not exported by "node_modules/path-to-regexp/dist/index.js", imported by "src/router.ts".
```

If I use the `const {match} = require('path-to-regexp');` then the build error is disapeared but i got a runtime error
`ReferenceError: require is not defined`

Node version: `v20.11.0`
NPM version: `10.2.4`
TypeScript version: `5.5.3`
Vite version: `5.3.3`
Vue version: `3.4.27`

Should I change something in my `tsconfig.json` or `vite.config.ts` files?

**Comment by blakeembrey** [comment]
Thanks for the report. I'm not too familiar with Vue/Vite but are you importing any other CommonJS packages and how do you use them? If it follows the old node.js spec for loading CommonJS packages, you might need to do `import pathToRegexp from "path-to-regexp";`.

Is that error from TypeScript or Vite though? It looks like Vite so I think your TypeScript config is fine (it probably has `esModuleInterop: true`?).

**Comment by tikaszvince** [comment]
If i change to `import pathToRegexp ...` i got a similar error:  `"default" is not exported by "node_modules/path-to-regexp/dist/index.js"`

The whole error with trace:

```
x Build failed in 834ms
error during build:
src/router.ts (3:7): "default" is not exported by "node_modules/path-to-regexp/dist/index.js", imported by "src/router.ts".
file: ./src/router.ts:3:7

2:
3: import pathToRegexp from "path-to-regexp";
          ^
    at getRollupError (file:///.../node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at error (file:///.../node_modules/rollup/dist/es/shared/parseAst.js:388:42)
    at Module.error (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:13827:16)
    at Module.traceVariable (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:14275:29)
    at ModuleScope.findVariable (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:11990:39)
    at FunctionScope.findVariable (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at FunctionBodyScope.findVariable (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
    at MemberExpression.bind (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:8773:49)
    at CallExpression.bind (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
    at CallExpression.bind (file:///.../node_modules/rollup/dist/es/shared/node-entry.js:9135:15)
```

My `package.json`
```JSON
{
  "name": "MY_PROJECT",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "run-p type-check \"build-only {@}\" --",
    "preview": "vite preview",
    "test:unit": "vitest run --coverage",
    "test:ui": "vitest --coverage --ui",
    "build-only": "vite build",
    "type-check": "vue-tsc --build --force",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore",
    "format": "prettier --write src/ tests/"
  },
  "dependencies": {
    "pinia": "^2.1.7",
    "vue": "^3.4.27",
    "vue-router": "^4.3.2",
    "vue-tippy": "^6.4.1"
  },
  "devDependencies": {
    "@rushstack/eslint-patch": "^1.10.3",
    "@tsconfig/node20": "^20.1.4",
    "@types/geojson": "^7946.0.14",
    "@types/jsdom": "^21.1.7",
    "@types/node": "^20.14.10",
    "@unhead/vue": "^1.9.15",
    "@vitejs/plugin-vue": "^5.0.5",
    "@vitest/coverage-v8": "^2.0.1",
    "@vitest/ui": "^2.0.1",
    "@vue/eslint-config-prettier": "^9.0.0",
    "@vue/eslint-config-typescript": "^13.0.0",
    "@vue/test-utils": "^2.4.6",
    "@vue/tsconfig": "^0.5.1",
    "axios": "^1.7.2",
    "eslint": "^8.57.0",
    "eslint-plugin-vue": "^9.27.0",
    "jsdom": "^24.1.0",
    "npm-run-all2": "^6.2.2",
    "path-to-regexp": "^7.0.0",
    "prettier": "^3.3.2",
    "sass": "^1.77.6",
    "typescript": "^5.5.3",
    "vite": "^5.3.3",
    "vite-plugin-static-copy": "^1.0.6",
    "vitest": "^2.0.1",
    "vue-tsc": "^2.0.26"
  }
}
```

My `tsconfig.json` indeed has `esModuleInterop: true`.

**Comment by tikaszvince** [comment]
For sake of SEO:

My `vite.config.ts` has containst the `build.comonjsOptions.extensions` setting. After I removed the `extensions` list this error is disappeared.

Before:
```TypeScript
export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {
    chunkSizeWarningLimit: 1000,
    sourcemap: true,
    minify: 'esbuild',
    emptyOutDir: true,
    commonjsOptions: {
      extensions: ['js']
    },
    target: ['es2021'],
  }
})
```

After:
```TypeScript
export default defineConfig({
  plugins: [
    vue(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {
    chunkSizeWarningLimit: 1000,
    sourcemap: true,
    minify: 'esbuild',
    emptyOutDir: true,
    // commonjsOptions: {
    //   extensions: ['js']
    // },
    target: ['es2021'],
  }
})
```
