### ISSUE TITLE
Neveste version 8.1.0 seems to break for instance express module

### ISSUE THREAD

**Issue by thomashohn** [pillarjs/path-to-regexp#322]
Hi 

Updated to express 5.0.0 and suddenly stuff seems to break in path-to-regexp.

/some-repo/node_modules/path-to-regexp/dist/index.js:85
            throw new TypeError(`Missing parameter name at ${i}: ${DEBUG_URL}`);
            ^

TypeError: Missing parameter name at 1: https://git.new/pathToRegexpError
    at name (/some-repo/node_modules/path-to-regexp/dist/index.js:85:19)
    at lexer (/some-repo/node_modules/path-to-regexp/dist/index.js:103:27)
    at lexer.next (<anonymous>)
    at Iter.peek (/some-repo/node_modules/path-to-regexp/dist/index.js:119:38)
    at Iter.tryConsume (/some-repo/node_modules/path-to-regexp/dist/index.js:125:28)
    at Iter.text (/some-repo/node_modules/path-to-regexp/dist/index.js:141:30)
    at consume (/some-repo/node_modules/path-to-regexp/dist/index.js:166:29)
    at parse (/some-repo/node_modules/path-to-regexp/dist/index.js:197:20)
    at /some-repo/node_modules/path-to-regexp/dist/index.js:308:74
    at Array.map (<anonymous>)

See also https://github.com/expressjs/express/issues/5948

**Comment by eMTyMe** [comment]
> how about `*.html` this kind of rule, `*anything.html` does not make sense, need something to wrap it?

No wrap needed, this bug was also fixed. Both of these routes are valid.

`*anything.html` is not very useful, but it does make sense.

**Comment by gokulsivan777** [comment]
app.route("/deleteUser/:Id?/")   how could i have a fix for this

**Comment by charbelMansourDev** [comment]
> Same issue here, it's because of any wildcard in a route,
> 
> To resolve this issue, write something after the asterisk.
> 
> Meaning change this
> 
> ```
> app.get("*", ....);
> // or
> app.get("/index/*");
> ```
> 
> to
> 
> ```
> app.get("*writeAnything", ...);
> // or
> app.get("/index/*youWantTo")
> ```

Yeeeees, very niiiiiice
