### ISSUE TITLE
Doesn't support capture groups?

### ISSUE THREAD

**Issue by jsumners-nr** [pillarjs/path-to-regexp#327]
```js
'use strict'

const {pathToRegexp} = require('path-to-regexp')
console.log(
  pathToRegexp('/:first/(.*)')
)
```

```
❯ node index.js
/whatever/node_modules/path-to-regexp/dist/index.js:136
        throw new TypeError(`Unexpected ${nextType} at ${index}, expected ${type}: ${DEBUG_URL}`);
        ^

TypeError: Unexpected ( at 8, expected END: https://git.new/pathToRegexpError
    at Iter.consume (/private/tmp/16/node_modules/path-to-regexp/dist/index.js:136:15)
    at consume (/private/tmp/16/node_modules/path-to-regexp/dist/index.js:193:16)
    at parse (/private/tmp/16/node_modules/path-to-regexp/dist/index.js:197:20)
    at /private/tmp/16/node_modules/path-to-regexp/dist/index.js:308:74
    at Array.map (<anonymous>)
    at pathToRegexp (/private/tmp/16/node_modules/path-to-regexp/dist/index.js:308:25)
    at Object.<anonymous> (/private/tmp/16/index.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)

Node.js v18.20.4
```

Am I missing something?

**Comment by blakeembrey** [comment]
That is correct, Express 5 does not support capture groups. There is documentation in [the link](https://git.new/pathToRegexpError) from the error you copied that may help, but if it doesn't please let me know and I'll try and improve the documentation.

**Comment by jsumners-nr** [comment]
I don't think I even saw the link. If I did, it didn't register to me as related.
