### ISSUE TITLE
path.replace is not a function

### ISSUE THREAD

**Issue by wll8** [pillarjs/path-to-regexp#333]
The new version of path-to-regexp is an incompatible update

- @httptoolkit/httpolyglot@2.2.1
- express@4.21.0
- mockm@1.1.27-alpha.7
- path-to-regexp@0.1.10

``` txt
TypeError: path must be a string, array of strings, or regular expression
    at pathToRegexp (C:\git2\mockm\server\node_modules\express\node_modules\path-to-regexp\index.js:69:11)
    at new Layer (C:\git2\mockm\server\node_modules\express\lib\router\layer.js:45:17)
    at Function.route (C:\git2\mockm\server\node_modules\express\lib\router\index.js:505:15)
    at app.<computed> [as bind] (C:\git2\mockm\server\node_modules\express\lib\application.js:498:30)
    at new Server (C:\git2\mockm\server\node_modules\@httptoolkit\httpolyglot\dist\index.js:36:47)
    at Object.createServer (C:\git2\mockm\server\node_modules\@httptoolkit\httpolyglot\dist\index.js:159:12)
    at Object.getHttpServer (C:\git2\mockm\server\util\business.js:68:56)
    at serverProxy (C:\git2\mockm\server\proxy.js:34:49)
    at C:\git2\mockm\server\server.js:46:24
```

![image](https://github.com/user-attachments/assets/331a45d3-0743-4811-84e2-ee35fb5c811a)

**Comment by GrahamCampbell** [comment]
`path-to-regexp@0.2.5` is not a new version.

**Comment by blakeembrey** [comment]
I won't be fixing this in `path-to-regexp` because this library was never intended to accept random objects as input. This appears to be a bug in `httpolyglot`, since `bind` has always been a HTTP method on that function and was not the native JS `bind`.

**Comment by blakeembrey** [comment]
It's a regrettable situation, but it appears that line never did what the authors intended and could be removed. I'd maybe suggest a PR removing this line: https://github.com/httptoolkit/httpolyglot/blob/8f726e1fce599b7a1444444cab396e818306c5b0/src/index.ts#L81

Alternatively if you write a wrapper function that has a real `bind` method, that would work too. E.g. `(req, res) => app(req, res);`.
